#ifndef _IBASEEVENTFUNCTION_
#define _IBASEEVENTFUNCTION_

namespace INVENT
{
	class IBaseEventFunction
	{
	public:
		friend class IEventLayer;

		IBaseEventFunction() = default;
		virtual ~IBaseEventFunction() = default;

	protected:
		virtual void EVENT_KEY_SPACE(float delta);
		virtual void EVENT_KEY_APOSTROPHE(float delta);
		virtual void EVENT_KEY_COMMA(float delta);
		virtual void EVENT_KEY_MINUS(float delta);
		virtual void EVENT_KEY_PERIOD(float delta);
		virtual void EVENT_KEY_SLASH(float delta);
		virtual void EVENT_KEY_0(float delta);
		virtual void EVENT_KEY_1(float delta);
		virtual void EVENT_KEY_2(float delta);
		virtual void EVENT_KEY_3(float delta);
		virtual void EVENT_KEY_4(float delta);
		virtual void EVENT_KEY_5(float delta);
		virtual void EVENT_KEY_6(float delta);
		virtual void EVENT_KEY_7(float delta);
		virtual void EVENT_KEY_8(float delta);
		virtual void EVENT_KEY_9(float delta);
		virtual void EVENT_KEY_SEMICOLON(float delta);
		virtual void EVENT_KEY_EQUAL(float delta);
		virtual void EVENT_KEY_A(float delta);
		virtual void EVENT_KEY_B(float delta);
		virtual void EVENT_KEY_C(float delta);
		virtual void EVENT_KEY_D(float delta);
		virtual void EVENT_KEY_E(float delta);
		virtual void EVENT_KEY_F(float delta);
		virtual void EVENT_KEY_G(float delta);
		virtual void EVENT_KEY_H(float delta);
		virtual void EVENT_KEY_I(float delta);
		virtual void EVENT_KEY_J(float delta);
		virtual void EVENT_KEY_K(float delta);
		virtual void EVENT_KEY_L(float delta);
		virtual void EVENT_KEY_M(float delta);
		virtual void EVENT_KEY_N(float delta);
		virtual void EVENT_KEY_O(float delta);
		virtual void EVENT_KEY_P(float delta);
		virtual void EVENT_KEY_Q(float delta);
		virtual void EVENT_KEY_R(float delta);
		virtual void EVENT_KEY_S(float delta);
		virtual void EVENT_KEY_T(float delta);
		virtual void EVENT_KEY_U(float delta);
		virtual void EVENT_KEY_V(float delta);
		virtual void EVENT_KEY_W(float delta);
		virtual void EVENT_KEY_X(float delta);
		virtual void EVENT_KEY_Y(float delta);
		virtual void EVENT_KEY_Z(float delta);
		virtual void EVENT_KEY_LEFT_BRACKET(float delta);
		virtual void EVENT_KEY_BACKSLASH(float delta);
		virtual void EVENT_KEY_RIGHT_BRACKET(float delta);
		virtual void EVENT_KEY_GRAVE_ACCENT(float delta);
		virtual void EVENT_KEY_WORLD_1(float delta);
		virtual void EVENT_KEY_WORLD_2(float delta);
		virtual void EVENT_KEY_ESCAPE(float delta);
		virtual void EVENT_KEY_ENTER(float delta);
		virtual void EVENT_KEY_TAB(float delta);
		virtual void EVENT_KEY_BACKSPACE(float delta);
		virtual void EVENT_KEY_INSERT(float delta);
		virtual void EVENT_KEY_DELETE(float delta);
		virtual void EVENT_KEY_RIGHT(float delta);
		virtual void EVENT_KEY_LEFT(float delta);
		virtual void EVENT_KEY_DOWN(float delta);
		virtual void EVENT_KEY_UP(float delta);
		virtual void EVENT_KEY_PAGE_UP(float delta);
		virtual void EVENT_KEY_PAGE_DOWN(float delta);
		virtual void EVENT_KEY_HOME(float delta);
		virtual void EVENT_KEY_END(float delta);
		virtual void EVENT_KEY_CAPS_LOCK(float delta);
		virtual void EVENT_KEY_SCROLL_LOCK(float delta);
		virtual void EVENT_KEY_NUM_LOCK(float delta);
		virtual void EVENT_KEY_PRINT_SCREEN(float delta);
		virtual void EVENT_KEY_PAUSE(float delta);
		virtual void EVENT_KEY_F1(float delta);
		virtual void EVENT_KEY_F2(float delta);
		virtual void EVENT_KEY_F3(float delta);
		virtual void EVENT_KEY_F4(float delta);
		virtual void EVENT_KEY_F5(float delta);
		virtual void EVENT_KEY_F6(float delta);
		virtual void EVENT_KEY_F7(float delta);
		virtual void EVENT_KEY_F8(float delta);
		virtual void EVENT_KEY_F9(float delta);
		virtual void EVENT_KEY_F10(float delta);
		virtual void EVENT_KEY_F11(float delta);
		virtual void EVENT_KEY_F12(float delta);
		virtual void EVENT_KEY_F13(float delta);
		virtual void EVENT_KEY_F14(float delta);
		virtual void EVENT_KEY_F15(float delta);
		virtual void EVENT_KEY_F16(float delta);
		virtual void EVENT_KEY_F17(float delta);
		virtual void EVENT_KEY_F18(float delta);
		virtual void EVENT_KEY_F19(float delta);
		virtual void EVENT_KEY_F20(float delta);
		virtual void EVENT_KEY_F21(float delta);
		virtual void EVENT_KEY_F22(float delta);
		virtual void EVENT_KEY_F23(float delta);
		virtual void EVENT_KEY_F24(float delta);
		virtual void EVENT_KEY_F25(float delta);
		virtual void EVENT_KEY_KP_0(float delta);
		virtual void EVENT_KEY_KP_1(float delta);
		virtual void EVENT_KEY_KP_2(float delta);
		virtual void EVENT_KEY_KP_3(float delta);
		virtual void EVENT_KEY_KP_4(float delta);
		virtual void EVENT_KEY_KP_5(float delta);
		virtual void EVENT_KEY_KP_6(float delta);
		virtual void EVENT_KEY_KP_7(float delta);
		virtual void EVENT_KEY_KP_8(float delta);
		virtual void EVENT_KEY_KP_9(float delta);
		virtual void EVENT_KEY_KP_DECIMAL(float delta);
		virtual void EVENT_KEY_KP_DIVIDE(float delta);
		virtual void EVENT_KEY_KP_MULTIPLY(float delta);
		virtual void EVENT_KEY_KP_SUBTRACT(float delta);
		virtual void EVENT_KEY_KP_ADD(float delta);
		virtual void EVENT_KEY_KP_ENTER(float delta);
		virtual void EVENT_KEY_KP_EQUAL(float delta);
		virtual void EVENT_KEY_LEFT_SHIFT(float delta);
		virtual void EVENT_KEY_LEFT_CONTROL(float delta);
		virtual void EVENT_KEY_LEFT_ALT(float delta);
		virtual void EVENT_KEY_LEFT_SUPER(float delta);
		virtual void EVENT_KEY_RIGHT_SHIFT(float delta);
		virtual void EVENT_KEY_RIGHT_CONTROL(float delta);
		virtual void EVENT_KEY_RIGHT_ALT(float delta);
		virtual void EVENT_KEY_RIGHT_SUPER(float delta);
		virtual void EVENT_KEY_MENU(float delta);

		virtual void EVENT_CURSOR_POSITION_FRAME(float delta, bool cursor_inside_window, double xpos, double ypos);

		virtual void PRESS_EVENT_KEY_SPACE();
		virtual void PRESS_EVENT_KEY_APOSTROPHE();
		virtual void PRESS_EVENT_KEY_COMMA();
		virtual void PRESS_EVENT_KEY_MINUS();
		virtual void PRESS_EVENT_KEY_PERIOD();
		virtual void PRESS_EVENT_KEY_SLASH();
		virtual void PRESS_EVENT_KEY_0();
		virtual void PRESS_EVENT_KEY_1();
		virtual void PRESS_EVENT_KEY_2();
		virtual void PRESS_EVENT_KEY_3();
		virtual void PRESS_EVENT_KEY_4();
		virtual void PRESS_EVENT_KEY_5();
		virtual void PRESS_EVENT_KEY_6();
		virtual void PRESS_EVENT_KEY_7();
		virtual void PRESS_EVENT_KEY_8();
		virtual void PRESS_EVENT_KEY_9();
		virtual void PRESS_EVENT_KEY_SEMICOLON();
		virtual void PRESS_EVENT_KEY_EQUAL();
		virtual void PRESS_EVENT_KEY_A();
		virtual void PRESS_EVENT_KEY_B();
		virtual void PRESS_EVENT_KEY_C();
		virtual void PRESS_EVENT_KEY_D();
		virtual void PRESS_EVENT_KEY_E();
		virtual void PRESS_EVENT_KEY_F();
		virtual void PRESS_EVENT_KEY_G();
		virtual void PRESS_EVENT_KEY_H();
		virtual void PRESS_EVENT_KEY_I();
		virtual void PRESS_EVENT_KEY_J();
		virtual void PRESS_EVENT_KEY_K();
		virtual void PRESS_EVENT_KEY_L();
		virtual void PRESS_EVENT_KEY_M();
		virtual void PRESS_EVENT_KEY_N();
		virtual void PRESS_EVENT_KEY_O();
		virtual void PRESS_EVENT_KEY_P();
		virtual void PRESS_EVENT_KEY_Q();
		virtual void PRESS_EVENT_KEY_R();
		virtual void PRESS_EVENT_KEY_S();
		virtual void PRESS_EVENT_KEY_T();
		virtual void PRESS_EVENT_KEY_U();
		virtual void PRESS_EVENT_KEY_V();
		virtual void PRESS_EVENT_KEY_W();
		virtual void PRESS_EVENT_KEY_X();
		virtual void PRESS_EVENT_KEY_Y();
		virtual void PRESS_EVENT_KEY_Z();
		virtual void PRESS_EVENT_KEY_LEFT_BRACKET();
		virtual void PRESS_EVENT_KEY_BACKSLASH();
		virtual void PRESS_EVENT_KEY_RIGHT_BRACKET();
		virtual void PRESS_EVENT_KEY_GRAVE_ACCENT();
		virtual void PRESS_EVENT_KEY_WORLD_1();
		virtual void PRESS_EVENT_KEY_WORLD_2();
		virtual void PRESS_EVENT_KEY_ESCAPE();
		virtual void PRESS_EVENT_KEY_ENTER();
		virtual void PRESS_EVENT_KEY_TAB();
		virtual void PRESS_EVENT_KEY_BACKSPACE();
		virtual void PRESS_EVENT_KEY_INSERT();
		virtual void PRESS_EVENT_KEY_DELETE();
		virtual void PRESS_EVENT_KEY_RIGHT();
		virtual void PRESS_EVENT_KEY_LEFT();
		virtual void PRESS_EVENT_KEY_DOWN();
		virtual void PRESS_EVENT_KEY_UP();
		virtual void PRESS_EVENT_KEY_PAGE_UP();
		virtual void PRESS_EVENT_KEY_PAGE_DOWN();
		virtual void PRESS_EVENT_KEY_HOME();
		virtual void PRESS_EVENT_KEY_END();
		virtual void PRESS_EVENT_KEY_CAPS_LOCK();
		virtual void PRESS_EVENT_KEY_SCROLL_LOCK();
		virtual void PRESS_EVENT_KEY_NUM_LOCK();
		virtual void PRESS_EVENT_KEY_PRINT_SCREEN();
		virtual void PRESS_EVENT_KEY_PAUSE();
		virtual void PRESS_EVENT_KEY_F1();
		virtual void PRESS_EVENT_KEY_F2();
		virtual void PRESS_EVENT_KEY_F3();
		virtual void PRESS_EVENT_KEY_F4();
		virtual void PRESS_EVENT_KEY_F5();
		virtual void PRESS_EVENT_KEY_F6();
		virtual void PRESS_EVENT_KEY_F7();
		virtual void PRESS_EVENT_KEY_F8();
		virtual void PRESS_EVENT_KEY_F9();
		virtual void PRESS_EVENT_KEY_F10();
		virtual void PRESS_EVENT_KEY_F11();
		virtual void PRESS_EVENT_KEY_F12();
		virtual void PRESS_EVENT_KEY_F13();
		virtual void PRESS_EVENT_KEY_F14();
		virtual void PRESS_EVENT_KEY_F15();
		virtual void PRESS_EVENT_KEY_F16();
		virtual void PRESS_EVENT_KEY_F17();
		virtual void PRESS_EVENT_KEY_F18();
		virtual void PRESS_EVENT_KEY_F19();
		virtual void PRESS_EVENT_KEY_F20();
		virtual void PRESS_EVENT_KEY_F21();
		virtual void PRESS_EVENT_KEY_F22();
		virtual void PRESS_EVENT_KEY_F23();
		virtual void PRESS_EVENT_KEY_F24();
		virtual void PRESS_EVENT_KEY_F25();
		virtual void PRESS_EVENT_KEY_KP_0();
		virtual void PRESS_EVENT_KEY_KP_1();
		virtual void PRESS_EVENT_KEY_KP_2();
		virtual void PRESS_EVENT_KEY_KP_3();
		virtual void PRESS_EVENT_KEY_KP_4();
		virtual void PRESS_EVENT_KEY_KP_5();
		virtual void PRESS_EVENT_KEY_KP_6();
		virtual void PRESS_EVENT_KEY_KP_7();
		virtual void PRESS_EVENT_KEY_KP_8();
		virtual void PRESS_EVENT_KEY_KP_9();
		virtual void PRESS_EVENT_KEY_KP_DECIMAL();
		virtual void PRESS_EVENT_KEY_KP_DIVIDE();
		virtual void PRESS_EVENT_KEY_KP_MULTIPLY();
		virtual void PRESS_EVENT_KEY_KP_SUBTRACT();
		virtual void PRESS_EVENT_KEY_KP_ADD();
		virtual void PRESS_EVENT_KEY_KP_ENTER();
		virtual void PRESS_EVENT_KEY_KP_EQUAL();
		virtual void PRESS_EVENT_KEY_LEFT_SHIFT();
		virtual void PRESS_EVENT_KEY_LEFT_CONTROL();
		virtual void PRESS_EVENT_KEY_LEFT_ALT();
		virtual void PRESS_EVENT_KEY_LEFT_SUPER();
		virtual void PRESS_EVENT_KEY_RIGHT_SHIFT();
		virtual void PRESS_EVENT_KEY_RIGHT_CONTROL();
		virtual void PRESS_EVENT_KEY_RIGHT_ALT();
		virtual void PRESS_EVENT_KEY_RIGHT_SUPER();
		virtual void PRESS_EVENT_KEY_MENU();

		virtual void RELEASE_EVENT_KEY_SPACE();
		virtual void RELEASE_EVENT_KEY_APOSTROPHE();
		virtual void RELEASE_EVENT_KEY_COMMA();
		virtual void RELEASE_EVENT_KEY_MINUS();
		virtual void RELEASE_EVENT_KEY_PERIOD();
		virtual void RELEASE_EVENT_KEY_SLASH();
		virtual void RELEASE_EVENT_KEY_0();
		virtual void RELEASE_EVENT_KEY_1();
		virtual void RELEASE_EVENT_KEY_2();
		virtual void RELEASE_EVENT_KEY_3();
		virtual void RELEASE_EVENT_KEY_4();
		virtual void RELEASE_EVENT_KEY_5();
		virtual void RELEASE_EVENT_KEY_6();
		virtual void RELEASE_EVENT_KEY_7();
		virtual void RELEASE_EVENT_KEY_8();
		virtual void RELEASE_EVENT_KEY_9();
		virtual void RELEASE_EVENT_KEY_SEMICOLON();
		virtual void RELEASE_EVENT_KEY_EQUAL();
		virtual void RELEASE_EVENT_KEY_A();
		virtual void RELEASE_EVENT_KEY_B();
		virtual void RELEASE_EVENT_KEY_C();
		virtual void RELEASE_EVENT_KEY_D();
		virtual void RELEASE_EVENT_KEY_E();
		virtual void RELEASE_EVENT_KEY_F();
		virtual void RELEASE_EVENT_KEY_G();
		virtual void RELEASE_EVENT_KEY_H();
		virtual void RELEASE_EVENT_KEY_I();
		virtual void RELEASE_EVENT_KEY_J();
		virtual void RELEASE_EVENT_KEY_K();
		virtual void RELEASE_EVENT_KEY_L();
		virtual void RELEASE_EVENT_KEY_M();
		virtual void RELEASE_EVENT_KEY_N();
		virtual void RELEASE_EVENT_KEY_O();
		virtual void RELEASE_EVENT_KEY_P();
		virtual void RELEASE_EVENT_KEY_Q();
		virtual void RELEASE_EVENT_KEY_R();
		virtual void RELEASE_EVENT_KEY_S();
		virtual void RELEASE_EVENT_KEY_T();
		virtual void RELEASE_EVENT_KEY_U();
		virtual void RELEASE_EVENT_KEY_V();
		virtual void RELEASE_EVENT_KEY_W();
		virtual void RELEASE_EVENT_KEY_X();
		virtual void RELEASE_EVENT_KEY_Y();
		virtual void RELEASE_EVENT_KEY_Z();
		virtual void RELEASE_EVENT_KEY_LEFT_BRACKET();
		virtual void RELEASE_EVENT_KEY_BACKSLASH();
		virtual void RELEASE_EVENT_KEY_RIGHT_BRACKET();
		virtual void RELEASE_EVENT_KEY_GRAVE_ACCENT();
		virtual void RELEASE_EVENT_KEY_WORLD_1();
		virtual void RELEASE_EVENT_KEY_WORLD_2();
		virtual void RELEASE_EVENT_KEY_ESCAPE();
		virtual void RELEASE_EVENT_KEY_ENTER();
		virtual void RELEASE_EVENT_KEY_TAB();
		virtual void RELEASE_EVENT_KEY_BACKSPACE();
		virtual void RELEASE_EVENT_KEY_INSERT();
		virtual void RELEASE_EVENT_KEY_DELETE();
		virtual void RELEASE_EVENT_KEY_RIGHT();
		virtual void RELEASE_EVENT_KEY_LEFT();
		virtual void RELEASE_EVENT_KEY_DOWN();
		virtual void RELEASE_EVENT_KEY_UP();
		virtual void RELEASE_EVENT_KEY_PAGE_UP();
		virtual void RELEASE_EVENT_KEY_PAGE_DOWN();
		virtual void RELEASE_EVENT_KEY_HOME();
		virtual void RELEASE_EVENT_KEY_END();
		virtual void RELEASE_EVENT_KEY_CAPS_LOCK();
		virtual void RELEASE_EVENT_KEY_SCROLL_LOCK();
		virtual void RELEASE_EVENT_KEY_NUM_LOCK();
		virtual void RELEASE_EVENT_KEY_PRINT_SCREEN();
		virtual void RELEASE_EVENT_KEY_PAUSE();
		virtual void RELEASE_EVENT_KEY_F1();
		virtual void RELEASE_EVENT_KEY_F2();
		virtual void RELEASE_EVENT_KEY_F3();
		virtual void RELEASE_EVENT_KEY_F4();
		virtual void RELEASE_EVENT_KEY_F5();
		virtual void RELEASE_EVENT_KEY_F6();
		virtual void RELEASE_EVENT_KEY_F7();
		virtual void RELEASE_EVENT_KEY_F8();
		virtual void RELEASE_EVENT_KEY_F9();
		virtual void RELEASE_EVENT_KEY_F10();
		virtual void RELEASE_EVENT_KEY_F11();
		virtual void RELEASE_EVENT_KEY_F12();
		virtual void RELEASE_EVENT_KEY_F13();
		virtual void RELEASE_EVENT_KEY_F14();
		virtual void RELEASE_EVENT_KEY_F15();
		virtual void RELEASE_EVENT_KEY_F16();
		virtual void RELEASE_EVENT_KEY_F17();
		virtual void RELEASE_EVENT_KEY_F18();
		virtual void RELEASE_EVENT_KEY_F19();
		virtual void RELEASE_EVENT_KEY_F20();
		virtual void RELEASE_EVENT_KEY_F21();
		virtual void RELEASE_EVENT_KEY_F22();
		virtual void RELEASE_EVENT_KEY_F23();
		virtual void RELEASE_EVENT_KEY_F24();
		virtual void RELEASE_EVENT_KEY_F25();
		virtual void RELEASE_EVENT_KEY_KP_0();
		virtual void RELEASE_EVENT_KEY_KP_1();
		virtual void RELEASE_EVENT_KEY_KP_2();
		virtual void RELEASE_EVENT_KEY_KP_3();
		virtual void RELEASE_EVENT_KEY_KP_4();
		virtual void RELEASE_EVENT_KEY_KP_5();
		virtual void RELEASE_EVENT_KEY_KP_6();
		virtual void RELEASE_EVENT_KEY_KP_7();
		virtual void RELEASE_EVENT_KEY_KP_8();
		virtual void RELEASE_EVENT_KEY_KP_9();
		virtual void RELEASE_EVENT_KEY_KP_DECIMAL();
		virtual void RELEASE_EVENT_KEY_KP_DIVIDE();
		virtual void RELEASE_EVENT_KEY_KP_MULTIPLY();
		virtual void RELEASE_EVENT_KEY_KP_SUBTRACT();
		virtual void RELEASE_EVENT_KEY_KP_ADD();
		virtual void RELEASE_EVENT_KEY_KP_ENTER();
		virtual void RELEASE_EVENT_KEY_KP_EQUAL();
		virtual void RELEASE_EVENT_KEY_LEFT_SHIFT();
		virtual void RELEASE_EVENT_KEY_LEFT_CONTROL();
		virtual void RELEASE_EVENT_KEY_LEFT_ALT();
		virtual void RELEASE_EVENT_KEY_LEFT_SUPER();
		virtual void RELEASE_EVENT_KEY_RIGHT_SHIFT();
		virtual void RELEASE_EVENT_KEY_RIGHT_CONTROL();
		virtual void RELEASE_EVENT_KEY_RIGHT_ALT();
		virtual void RELEASE_EVENT_KEY_RIGHT_SUPER();
		virtual void RELEASE_EVENT_KEY_MENU();

		virtual void EVENT_CURSOR_POSITION(double xpos, double ypos);

		virtual void PRESS_EVENT_MOUSE_BUTTON_LEFT(double xpos, double ypos);
		virtual void RELEASE_EVENT_MOUSE_BUTTON_LEFT(double xpos, double ypos);

		virtual void  PRESS_EVENT_MOUSE_BUTTON_RIGHT(double xpos, double ypos);
		virtual void  RELEASE_EVENT_MOUSE_BUTTON_RIGHT(double xpos, double ypos);
		virtual void  PRESS_EVENT_MOUSE_BUTTON_MIDDLE(double xpos, double ypos);
		virtual void  RELEASE_EVENT_MOUSE_BUTTON_MIDDLE(double xpos, double ypos);
		virtual void  PRESS_EVENT_MOUSE_BUTTON_4(double xpos, double ypos);
		virtual void  RELEASE_EVENT_MOUSE_BUTTON_4(double xpos, double ypos);
		virtual void  PRESS_EVENT_MOUSE_BUTTON_5(double xpos, double ypos);
		virtual void  RELEASE_EVENT_MOUSE_BUTTON_5(double xpos, double ypos);
		virtual void  PRESS_EVENT_MOUSE_BUTTON_6(double xpos, double ypos);
		virtual void  RELEASE_EVENT_MOUSE_BUTTON_6(double xpos, double ypos);
		virtual void  PRESS_EVENT_MOUSE_BUTTON_7(double xpos, double ypos);
		virtual void  RELEASE_EVENT_MOUSE_BUTTON_7(double xpos, double ypos);
		virtual void  PRESS_EVENT_MOUSE_BUTTON_8(double xpos, double ypos);
		virtual void  RELEASE_EVENT_MOUSE_BUTTON_8(double xpos, double ypos);

		virtual void EVNET_SCROLL(double cursor_xpos, double cursor_ypos, double xoffset, double yoffset);
	};
}

#endif // !_IBASEEVENTFUNCTION_
